version: '2'

networks:
    bibbox-default-network:
      external: true

services:
  §§INSTANCE-adminer:
    image: bibbox/adminer
    container_name:  §§INSTANCE-adminer
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "§§PORT:80"